### ISSUE TITLE
genproto 报错了

### ISSUE THREAD

**Issue by dmhai** [qaqzzl/free-im#2]
[root@VM-16-16-centos free-im]# ./run.sh
go: google.golang.org/genproto@v0.0.0-20200526211855-cb27e3aa2013 requires
	google.golang.org/protobuf@v1.23.1-0.20200526195155-81db48ad09cc: invalid version: git fetch --unshallow -f origin in /root/go/pkg/mod/cache/vcs/a6c5d6b8734f41936247415390043c979295646fadef73c39eedc1735cd0fef4: exit status 128:
	fatal: git fetch-pack: expected shallow list
go: google.golang.org/genproto@v0.0.0-20200526211855-cb27e3aa2013 requires
	google.golang.org/protobuf@v1.23.1-0.20200526195155-81db48ad09cc requires
	github.com/golang/protobuf@v1.4.0 requires
	google.golang.org/protobuf@v1.21.0 requires
	github.com/golang/protobuf@v1.4.0-rc.4.0.20200313231945-b860323f09d0: invalid version: git fetch --unshallow -f origin in /root/go/pkg/mod/cache/vcs/6e18cbff36266c74e48dd81b4b672026ac74fb69c838ddb6240f256bb8edf590: exit status 128:
	fatal: git fetch-pack: expected shallow list
go: google.golang.org/genproto@v0.0.0-20200526211855-cb27e3aa2013 requires
	google.golang.org/protobuf@v1.23.1-0.20200526195155-81db48ad09cc requires
	github.com/golang/protobuf@v1.4.0 requires
	google.golang.org/protobuf@v1.21.0 requires
	github.com/golang/protobuf@v1.4.0-rc.4.0.20200313231945-b860323f09d0: invalid version: git fetch --unshallow -f origin in /root/go/pkg/mod/cache/vcs/6e18cbff36266c74e48dd81b4b672026ac74fb69c838ddb6240f256bb8edf590: exit status 128:
	fatal: git fetch-pack: expected shallow list
go: google.golang.org/genproto@v0.0.0-20200526211855-cb27e3aa2013 requires
	google.golang.org/protobuf@v1.23.1-0.20200526195155-81db48ad09cc requires
	github.com/golang/protobuf@v1.4.0 requires
	google.golang.org/protobuf@v1.21.0 requires
	github.com/golang/protobuf@v1.4.0-rc.4.0.20200313231945-b860323f09d0: invalid version: git fetch --unshallow -f origin in /root/go/pkg/mod/cache/vcs/6e18cbff36266c74e48dd81b4b672026ac74fb69c838ddb6240f256bb8edf590: exit status 128:
	fatal: git fetch-pack: expected shallow list

**Comment by qaqzzl** [comment]
升级你的git版本， 应该会解决这个问题

**Comment by dmhai** [comment]
嗯嗯。好像是git的问题，我升级之后，后面好像没有这个问题了。

再问两个点。
1.我运行完了 ./run.sh 这步，显示：
启动进程: http_app
启动进程: logic
启动进程: tcp_conn
启动进程: ws_conn
这四行，服务端就算是部署完毕了吗？

2.有打算写web客户端对接的demo吗？我也看不懂app开发...
具体业务功能以后我自己慢慢来都行，但是整体框架怎么对接。
比如web端怎么请求，怎么回调，怎么心跳，怎么意外断开重连之类的。

木有客户端，花了一整天在这个上面，最终还没看到一个hello world ...  QAQ

**Comment by qaqzzl** [comment]
是的，服务端启动了，最近有写web客户端的计划，但是本人前端技术实在拉垮，什么时候能写出来还不知道，有兴趣的话，可以参与到这个项目中来，我们一起完成

**Comment by qaqzzl** [comment]
> 嗯嗯。好像是git的问题，我升级后，好像没有这个问题了。
> 
> 再问两个问题。
> 1.我运行完了./run.sh的步，显示：
> 启动进程：http_app
> 启动进程：逻辑
> 启动进程：tcp_conn
> 启动进程：ws_conn
> 这四行，服务端部署完毕？
> 
> 2.打算写web客户端对接demo吗？我也不懂app开发...
> 具体业务功能后，我慢慢来，但整体框架怎么对接。
> 比如web端怎么请求，怎么回调，心跳，怎么意外断重连等。
> 
> 客户端没有，花了一整天的光头，最终没有看到一个hello世界......QAQ

是的，服务端启动了，最近有写web客户端的计划，但是本人前端技术实在拉垮，什么时候能写出来还不知道，有兴趣的话，可以参与到这个项目中来，我们一起完成

**Comment by qaqzzl** [comment]
点错把你的评论删除了。。。。
是的，服务端启动了，最近有写web客户端的计划，但是本人前端技术实在拉垮，什么时候能写出来还不知道，有兴趣的话，可以参与到这个项目中来，我们一起完成
